version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - SECRET_KEY
      - ALGORITHM
      - ACCESS_TOKEN_EXPIRE_MINUTES
      - MONGODB_URI
      - GEMINI_API_KEY
      - QDRANT_HOST
      - QDRANT_PORT
      - QDRANT_API_KEY
      - LANGCHAIN_TRACING_V2
      - LANGSMITH_ENDPOINT
      - LANGSMITH_API_KEY
      - LANGSMITH_PROJECT
    restart: always
